# This is a basic workflow to help you get started with Actions

name: DevCard

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    # A schedule, which acts as a cronjob and will return every {x} time. 
    # It runs every night at 00:00.
    - cron: "0 0 * * *"

jobs:
# Daily.dev card
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.6
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_branch: devcard
          commit_message: "chore: update ${filename}"

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: github-metrics
          committer_message: "build: update `${filename}`"

          # Options
          user: agnelnieves
          template: classic
          base: header, activity, community
          # config_timezone: Europe/Oslo

          # Language plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_threshold: B

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>150
          plugin_notable_repositories: yes
